#ifndef __GEM_H__
#define __GEM_H__

#include <aes.h>
#include <vdi.h>

#ifdef __USE_REENTRANT

#include <mt_aes.h>

#define appl_bvset( disks, harddisks ) mt_appl_bvset(disks, harddisks, aes_global)
#define appl_control(a, b, c) mt_appl_control(a, b, c, aes_global)
#define appl_init()  mt_appl_init( aes_global )
#define appl_read( a, b, c )  mt_appl_read( a, b, c, aes_global )
#define appl_write( a, b, c )  mt_appl_write( a, b, c, aes_global )
#define appl_find( a )  mt_appl_find( a, aes_global )
#define appl_tplay( a, b, c )  mt_appl_tplay( a, b, c, aes_global )
#define appl_trecord( a, b )  mt_appl_trecord( a, b, aes_global )
#define appl_exit()  mt_appl_exit( aes_global )
#define appl_search( a, b, c, d )  mt_appl_search( a, b, c, d, aes_global )
#define appl_getinfo( a, b, c, d, e )  mt_appl_getinfo( a, b, c, d, e, aes_global )
#define appl_xgetinfo( a, b, c, d, e )  mt_appl_getinfo( a, b, c, d, e, aes_global )
#define appl_getinfo_str( a, b, c, d, e )  mt_appl_getinfo_str( a, b, c, d, e, aes_global )
#define appl_yield()  mt_appl_yield( aes_global )

#define evnt_keybd()  mt_evnt_keybd( aes_global )
#define evnt_button( a, b, c, d, e, f, g )  mt_evnt_button( a, b, c, d, e, f, g, aes_global )
#define evnt_button_event( a, b, c, d )  mt_evnt_button_event( a, b, c, d, aes_global )
#define evnt_mouse( a, b, c, d, e, f, g, h )  mt_evnt_mouse( a, b, c, d, e, f, g, h, aes_global )
#define evnt_mouse_event( a, b, c )  mt_evnt_mouse( a, b, c, aes_global )
#define evnt_mesag( a )  mt_evnt_mesag( a, aes_global )
#define evnt_multi(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,hilo,q,r,s,t,u,v) \
										mt_evnt_multi(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,hilo,q,r,s,t,u,v,aes_global)
#define evnt_timer(hilo)					mt_evnt_timer(hilo,aes_global)
#define evnt_dclick( a, b )  mt_evnt_dclick( a, b, aes_global )

#define menu_bar( a, b )  mt_menu_bar( a, b, aes_global )
#define menu_icheck( a, b, c )  mt_menu_icheck( a, b, c, aes_global )
#define menu_ienable( a, b, c )  mt_menu_ienable( a, b, c, aes_global )
#define menu_tnormal( a, b, c )  mt_menu_tnormal( a, b, c, aes_global )
#define menu_text( a, b, c )  mt_menu_text( a, b, c, aes_global )
#define menu_register( a, b )  mt_menu_register( a, b, aes_global )
#define menu_popup( a, b, c, d )  mt_menu_popup( a, b, c, d, aes_global )
#define menu_attach( a, b, c, d )  mt_menu_attach( a, b, c, d, aes_global )
#define menu_istart( a, b, c, d )  mt_menu_istart( a, b, c, d, aes_global )
#define menu_settings( a, b )  mt_menu_settings( a, b, aes_global )
#define menu_unregister( a )  mt_menu_unregister( a, aes_global )
#define menu_click( a, b )  mt_menu_click( a, b, aes_global )

#define objc_add( a, b, c )  mt_objc_add( a, b, c, aes_global )
#define objc_delete( a, b )  mt_objc_delete( a, b, aes_global )
#define objc_draw( a, b, c, d, e, f, g )  mt_objc_draw( a, b, c, d, e, f, g, aes_global )
#define objc_draw_grect( a, b, c, d )  mt_objc_draw_grect( a, b, c, d, aes_global )
#define objc_find( a, b, c, d, e )  mt_objc_find( a, b, c, d, e, aes_global )
#define objc_xfind( a, b, c, d, e )  mt_objc_xfind( a, b, c, d, e, aes_global )
#define objc_offset( a, b, c, d )  mt_objc_offset( a, b, c, d, aes_global )
#define objc_order( a, b, c )  mt_objc_order( a, b, c, aes_global )
#define objc_edit( a, b, c, d, e )  mt_objc_edit( a, b, c, d, e, aes_global )
#define objc_xedit( a, b, c, d, e, f )  mt_objc_xedit( a, b, c, d, e, f, aes_global )
#define objc_change( a, b, c, d, e, f, g, h, i )  mt_objc_change( a, b, c, d, e, f, g, h, i, aes_global )
#define objc_change_grect( a, b, c, d, e, f )  mt_objc_change_grect( a, b, c, d, e, f, aes_global )
#define objc_sysvar( a, b, c, d, e, f )  mt_objc_sysvar( a, b, c, d, e, f, aes_global )

#define objc_wdraw( a, b, c, d, e )  mt_objc_wdraw( a, b, c, d, e, aes_global )
#define objc_wchange( a, b, c, d, e )  mt_objc_wchange( a, b, c, d, e, aes_global )
#define graf_wwatchbox( a, b, c, d, e )  mt_graf_wwatchbox( a, b, c, d, e, aes_global )
#define form_wbutton( a, b, c, d, e )  mt_form_wbutton( a, b, c, d, e, aes_global )
#define form_wkeybd( a, b, c, d, e, f, g )  mt_form_wkeybd( a, b, c, d, e, f, g, aes_global )
#define objc_wedit( a, b, c, d, e, f )  mt_objc_wedit( a, b, c, d, e, f, aes_global )

#define form_do( a, b )  mt_form_do( a, b, aes_global )
#define form_xdo( a, b, c, d, e )  mt_form_xdo( a, b, c, d, e, aes_global )
#define form_dial( a, b, c )  mt_form_dial( a, b, c, aes_global )
#define form_xdial( a, b, c, d )  mt_form_xdial( a, b, c, d, aes_global )
#define form_xdial_grect(a,b,c,d)		mt_form_xdial_grect(a,b,c,d,aes_global)
#define form_alert( a, b )  mt_form_alert( a, b, aes_global )
#define form_error( a )  mt_form_error( a, aes_global )
#define form_center( a, b )  mt_form_center( a, b, aes_global )
#define form_keybd( a, b, c, d, e, f )  mt_form_keybd( a, b, c, d, e, f, aes_global )
#define form_button( a, b, c, d )  mt_form_button( a, b, c, d, aes_global )
#define form_popup( a, b, c )  mt_form_popup( a, b, c, aes_global )
#define xfrm_popup( a, b, c, d, e, f, g, h, i )  mt_xfrm_popup( a, b, c, d, e, f, g, h, i, aes_global )
#define form_xerr( a, b )  mt_form_xerr( a, b, aes_global )

#define graf_rubbox( a, b, c, d, e, f )  mt_graf_rubberbox( a, b, c, d, e, f, aes_global )
#define graf_dragbox( a, b, c, d, e, f, g, h, i, j )  mt_graf_dragbox_grect( a, b, c, d, e, f, g, h, i, j, aes_global )
#define graf_dragbox_grect( a, b, c, d, e, f, g )  mt_graf_dragbox( a, b, c, d, e, f, g, aes_global )
#define graf_movebox( a, b, c, d, e, f )  mt_graf_movebox( a, b, c, d, e, f, aes_global )
#define graf_growbox( a, b, c, d, e, f, g, h )  mt_graf_growbox(a,b, c, d, e, f, g, h, aes_global )
#define graf_growbox_grect( a, b )  mt_graf_growbox_rect(a,b, aes_global )
#define graf_shrinkbox( a, b, c, d, e, f, g, h )  mt_graf_shrinkbox(a,b, c, d, e, f, g, h, aes_global )
#define graf_shrinkbox_grect( a, b )  mt_graf_shrinkbox_grect(a,b, aes_global )
#define graf_watchbox( a, b, c, d )  mt_graf_watchbox( a, b, c, d, aes_global )
#define graf_slidebox( a, b, c, d )  mt_graf_slidebox( a, b, c, d, aes_global )
#define graf_handle( a, b, c, d )  mt_graf_handle( a, b, c, d, aes_global )
#define graf_xhandle( a, b, c, d, e )  mt_graf_xhandle( a, b, c, d, e, aes_global )
#define graf_mouse( a, b )  mt_graf_mouse( a, b, aes_global )
#define graf_mkstate( a )  mt_graf_mkstate( a, aes_global )
#define graf_multirubber( a, b, c, d, e, f, g )  mt_graf_multirubber( a, b, c, d, e, f, g, aes_global )

#define scrp_read( a )  mt_scrp_read( a, aes_global )
#define scrp_write( a )  mt_scrp_write( a, aes_global )
#define scrp_clear()  mt_scrp_clear( aes_global )

#define fsel_input( a, b, c )  mt_fsel_input( a, b, c, aes_global )
#define fsel_exinput( a, b, c, d )  mt_fsel_exinput( a, b, c, d, aes_global )
#define fsel_boxinput( a, b, c, d, e )  mt_fsel_boxinput( a, b, c, d, e, aes_global )

#define wind_create( a, b, c, d, e )  mt_wind_create( a, b, c, d, e, aes_global )
#define wind_calc( a, b, c, d, e, f, g, h, i, j )  mt_wind_calc( a, b, c, d, e f, g, h, i, j, aes_global )
#define wind_open( a, b, c, d, e )  mt_wind_open( a, b, c, d, e, aes_global )
#define wind_close( a )  mt_wind_close( a, aes_global )
#define wind_delete( a )  mt_wind_delete( a, aes_global )
#define wind_get( a, b, c, d, e, f )  mt_wind_get( a, b, c, d, e, f, aes_global )
#define wind_get_grect( a, b, c )  mt_wind_get_grect( a, b, c, aes_global )
#define wind_get_ptr( a, b, c )  mt_wind_get_ptr( a, b, c, aes_global )
#define wind_get_int( a, b, c )  mt_wind_get_int( a, b, c, aes_global )
#define wind_new() mt_wind_new(aes_global)
#define wind_set( a, b, c, d, e, f )  mt_wind_set( a, b, c, d, e, f, aes_global )
#define wind_set_str( a, b, c )  mt_wind_set_str( a, b, c, aes_global )
#define wind_set_ptr( a, b, c, d )  mt_wind_set_ptr( a, b, c, d, aes_global )
#define wind_set_int( a, b, c )  mt_wind_set_int( a, b, c, aes_global )
#define wind_set_grect( a, b, c )  mt_wind_set_grect( a, b, c, aes_global )
#define wind_set_ptr_int( a, b, c, d )  mt_wind_set_ptr_int( a, b, c, d, aes_global )
#define wind_find( a, b )  mt_wind_find( a, b, aes_global )
#define wind_update( a )  mt_wind_update( a, aes_global )

#define wind_create_grect( a, b )  mt_wind_create_grect( a, b, aes_global )
#define wind_xcreate_grect( a, b, c )  mt_wind_xcreate_grect( a, b, c, aes_global )
#define wind_calc_grect( a, b, c, d )  mt_wind_calc_grect( a, b, c, d, aes_global )
#define wind_open_grect( a, b )  mt_wind_open_grect( a, b, aes_global )
#define wind_xget(a, b, c, d, e, f, g, h, i, j) mt_wind_xget(a, b, c, d, e, f, g, h, i, j, aes_global)
#define wind_xget_grect(a, b, c, d) mt_wind_xget_grect(a, b, c, d, aes_global)
#define wind_xset(a, b, c, d, e, f, g, h, i, j) mt_wind_xset(a, b, c, d, e, f, g, h, i, j, aes_global)
#define wind_xset_grect(a, b, c, d) mt_wind_xset_grect(a, b, c, d, aes_global)

#define rsrc_load( a )  mt_rsrc_load( a, aes_global )
#define rsrc_free()  mt_rsrc_free( aes_global )
#define rsrc_gaddr( a, b, c )  mt_rsrc_gaddr( a, b, c, aes_global )
#define rsrc_saddr( a, b, c )  mt_rsrc_saddr( a, b, c, aes_global )
#define rsrc_obfix( a, b )  mt_rsrc_obfix( a, b, aes_global )
#define rsrc_rcfix( a )  mt_rsrc_rcfix( a, aes_global )

#define shel_read( a, b )  mt_shel_read( a, b, aes_global )
#define shel_write( a, b, c, d, e )  mt_shel_write( a, b, c, d, e, aes_global )
#define shel_get( a, b )  mt_shel_get( a, b, aes_global )
#define shel_help( a, b, c )  mt_shel_help( a, b, c, aes_global )
#define shel_put( a, b)  mt_shel_put( a, b, aes_global )
#define shel_find( a )  mt_shel_find( a, aes_global )
#define shel_envrn( a, b)  mt_shel_envrn( a, b, aes_global )
#define shel_rdef( a, b )  mt_shel_rdef( a, b, aes_global )
#define shel_wdef( a, b )  mt_shel_wdef( a, b, aes_global )

#define wdlg_create( a, b, c, d, e, f )  mt_wdlg_create( a, b, c, d, e, f, aes_global )
#define wdlg_open( a, b, c, d, e, f, g )  mt_wdlg_open( a, b, c, d, e, f, g, aes_global )
#define wdlg_close( a, b, c )  mt_wdlg_close( a, b, c, aes_global )
#define wdlg_delete( a )  mt_wdlg_delete( a, aes_global )
#define wdlg_get_tree( a, b, c )  mt_wdlg_get_tree( a, b, c, aes_global )
#define wdlg_get_edit( a, b )  mt_wdlg_get_edit( a, b, aes_global )
#define wdlg_get_udata( a )  mt_wdlg_get_udata( a, aes_global )
#define wdlg_get_handle( a )  mt_wdlg_get_handle( a, aes_global )
#define wdlg_set_edit( a, b )  mt_wdlg_set_edit( a, b, aes_global )
#define wdlg_set_tree( a, b )  mt_wdlg_set_tree( a, b, aes_global )
#define wdlg_set_size( a, b )  mt_wdlg_set_size( a, b, aes_global )
#define wdlg_set_iconify( a, b, c, d, e )  mt_wdlg_set_iconify( a, b, c, d, e, aes_global )
#define wdlg_set_uniconify( a, b, c, d )  mt_wdlg_set_uniconify( a, b, c, d, aes_global )
#define wdlg_evnt( a, b )  mt_wdlg_evnt( a, b, aes_global )
#define wdlg_redraw( a, b, c, d )  mt_wdlg_redraw( a, b, c, d, aes_global )


#define lbox_create( a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p )  mt_lbox_create( a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, aes_global )
#define lbox_update( a, b )  mt_lbox_update( a, b, aes_global )
#define lbox_do( a, b )  mt_lbox_do( a, b, aes_global )
#define lbox_delete( a )  mt_lbox_delete( a, aes_global )

#define lbox_cnt_items( a )  mt_lbox_cnt_items( a, aes_global )
#define lbox_get_tree( a )  mt_lbox_get_tree( a, aes_global )
#define lbox_get_avis( a )  mt_lbox_get_avis( a, aes_global )
#define lbox_get_udata( a )  mt_lbox_get_udata( a, aes_global )
#define lbox_get_afirst( a )  mt_lbox_get_afirst( a, aes_global )
#define lbox_get_slct_idx( a )  mt_lbox_get_slct_idx( a, aes_global )
#define lbox_get_items( a )  mt_lbox_get_items( a, aes_global )
#define lbox_get_item( a, b )  mt_lbox_get_item( a, b, aes_global )
#define lbox_get_slct_item( a )  mt_lbox_get_slct_item( a, aes_global )
#define lbox_get_idx( a, b )  mt_lbox_get_idx( a, b, aes_global )
#define lbox_get_bvis( a )  mt_lbox_get_bvis( a, aes_global )
#define lbox_get_bentries( a )  mt_lbox_get_bentries( a, aes_global )
#define lbox_get_bfirst( a )  mt_lbox_get_bfirst( a, aes_global )

#define lbox_set_asldr( a, b, c )  mt_lbox_set_asldr( a, b, c, aes_global )
#define lbox_set_items( a, b )  mt_lbox_set_items( a, b, aes_global )
#define lbox_free_items( a )  mt_lbox_free_items( a, aes_global )
#define lbox_free_list( a )  mt_lbox_free_list( a, aes_global )
#define lbox_ascroll_to( a, b, c, d )  mt_lbox_ascroll_to( a, b, c, d, aes_global )
#define lbox_set_bsldr( a, b, c )  mt_lbox_set_bsldr( a, b, c, aes_global )
#define lbox_set_bentries( a, b )  mt_lbox_set_bentries( a, b, aes_global )
#define lbox_bscroll_to( a, b, c, d )  mt_lbox_bscroll_to( a, b, c, d, aes_global )

#define fnts_create( a, b, c, d, e, f )  mt_fnts_create( a, b, c, d, e, f, aes_global )
#define fnts_delete( a, b )  mt_fnts_delete( a, b, aes_global )
#define fnts_open( a, b, c, d, e, f, g )  mt_fnts_open( a, b, c, d, e, f, g, aes_global )
#define fnts_close( a, b, c )  mt_fnts_close( a, b, c, aes_global )

#define fnts_get_no_styles( a, b )  mt_fnts_get_no_styles( a, b, aes_global )
#define fnts_get_style( a, b, c )  mt_fnts_get_style( a, b, c, aes_global )
#define fnts_get_name( a, b, c, d, e )  mt_fnts_get_name( a, b, c, d, e, aes_global )
#define fnts_get_info( a, b, c, d )  mt_fnts_get_info( a, b, c, d, aes_global )

#define fnts_add( a, b )  mt_fnts_add( a, b, aes_global )
#define fnts_remove( a )  mt_fnts_remove( a, aes_global )
#define fnts_update( a, b, c, d, e )  mt_fnts_update( a, b, c, d, e, aes_global )

#define fnts_evnt( a, b, c, d, e, f, g )  mt_fnts_evnt( a, b, c, d, e, f, g, aes_global )
#define fnts_do( a, b, c, d, e, f, g, h, i )  mt_fnts_do( a, b, c, d, e, f, g, h, i, aes_global )

#define pdlg_create( a )  mt_pdlg_create( a, aes_global )
#define pdlg_delete( a )  mt_pdlg_delete( a, aes_global )
#define pdlg_open( a, b, c, d, e, f )  mt_pdlg_open( a, b, c, d, e, f, aes_global )
#define pdlg_close( a, b, c )  mt_pdlg_close( a, b, c, aes_global )

#define pdlg_get_setsize()  mt_pdlg_get_setsize( aes_global )

#define pdlg_add_printers( a, b )  mt_pdlg_add_printers( a, b, aes_global )
#define pdlg_remove_printers( a )  mt_pdlg_remove_printers( a, aes_global )
#define pdlg_update( a, b )  mt_pdlg_update( a, b, aes_global )
#define pdlg_add_sub_dialogs( a, b )  mt_pdlg_add_sub_dialogs( a, b, aes_global )
#define pdlg_remove_sub_dialogs( a )  mt_pdlg_remove_sub_dialogs( a, aes_global )
#define pdlg_new_settings( a )  mt_pdlg_new_settings( a, aes_global )
#define pdlg_free_settings( a )  mt_pdlg_free_settings( a, aes_global )
#define pdlg_dflt_settings( a, b )  mt_pdlg_dflt_settings( a, b, aes_global )
#define pdlg_validate_settings( a, b )  mt_pdlg_validate_settings( a, b, aes_global )
#define pdlg_use_settings( a, b )  mt_pdlg_use_settings( a, b, aes_global )
#define pdlg_save_default_settings( a, b )  mt_pdlg_save_default_settings( a, b, aes_global )

#define pdlg_evnt( a, b, c, d )  mt_pdlg_evnt( a, b, c, d, aes_global )
#define pdlg_do( a, b, c, d )  mt_pdlg_do( a, b, c, d, aes_global )

#define fslx_open(a,b,c,d,e,f,g,h,i,j,k,l,m)  mt_fslx_open(a,b,c,d,e,f,g,h,i,j,k,l,m,aes_global)
#define fslx_evnt(a,b,c,d,e,f,g,h)  mt_fslx_evnt(a,b,c,d,e,f,g,h,aes_global)
#define fslx_do(a,b,c,d,e,f,g,h,i,j,k,l,m)  mt_fslx_do(a,b,c,d,e,f,g,h,i,j,k,l,m,aes_global)
#define fslx_close( a )  mt_fslx_close( a, aes_global )
#define fslx_set_flags( a, b )  mt_fslx_set_flags( a, b, aes_global )
#define fslx_getnxtfile(a,b)					mt_fslx_getnxtfile(a,b,aes_global)

#define edit_create() mt_edit_create(aes_global)
#define edit_open(a,b) mt_edit_open(a,b,aes_global)
#define edit_close(a,b) mt_edit_close(a,b,aes_global)
#define edit_delete(a) mt_edit_delete(a,aes_global)
#define edit_cursor(a,b,c,d) mt_edit_cursor(a,b,c,d,aes_global)
#define edit_evnt(a,b,c,d,e) mt_edit_evnt(a,b,c,d,e,aes_global)
#define edit_get_buf(a,b,c,d,e) mt_edit_get_buf(a,b,c,d,e,aes_global)
#define edit_set_buf(a,b,c,d) mt_edit_set_buf(a,b,c,d,aes_global)
#define edit_get_color(a,b,c,d) mt_edit_get_color(a,b,c,d,aes_global)
#define edit_get_cursor(a,b,c) mt_edit_get_cursor(a,b,c,aes_global)
#define edit_set_format(a,b,c,d) mt_edit_set_format(a,b,c,d,aes_global)
#define edit_get_format(a,b,c,d) mt_edit_get_format(a,b,c,d,aes_global)
#define edit_set_font(a,b,c,d,e,f) mt_edit_set_font(a,b,c,d,e,f,aes_global)
#define edit_get_font(a,b,c,d,e,f) mt_edit_get_font(a,b,c,d,e,f,aes_global)
#define edit_set_color(a,b,c,d) mt_edit_set_color(a,b,c,d,aes_global)
#define edit_set_cursor(a,b,c) mt_edit_set_cursor(a,b,c,aes_global)
#define edit_resized(a,b,c,d) mt_edit_resized(a,b,c,d,aes_global)
#define edit_get_dirty(a,b) mt_edit_get_dirty(a,b,aes_global)
#define edit_set_dirty(a,b,c) mt_edit_set_dirty(a,b,c,aes_global)
#define edit_get_sel(a,b,c,d) mt_edit_get_sel(a,b,c,d,aes_global)
#define edit_get_pos(a,b,c,d,e,f,g,h) mt_edit_get_pos(a,b,c,d,e,f,g,h,aes_global)
#define edit_set_pos(a,b,c,d,e,f,g,h) mt_edit_set_pos(a,b,c,d,e,f,g,h,aes_global)
#define edit_get_scrollinfo(a,b,c,d,e,f,g,h,i) mt_edit_get_scrollinfo(a,b,c,d,e,f,g,h,i,aes_global)
#define edit_scroll(a,b,c,d,e) mt_edit_scroll(a,b,c,d,e,aes_global)

#define xgrf_stepcalc( a, b, c, d, e, f, g, h, i, j, k ) mt_xgrf_stepcalc(a, b, c, d, e, f, g, h, i, j, k, aes_global)
#define xgrf_2box( a, b, c, d, e, f, g, h, i ) mt_xgrf_2box( a, b, c, d, e, f, g, h, i, aes_global )

#endif

#endif /* __GEM_H__ */
