
err_1s:  DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Allgemeiner Fehler',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Erreur g',$82,'n',$82,'rale',0
         DC.B                        -1,'General error',0
err_02s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Laufwerk nicht bereit',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Lecteur non pr',$85,'t',0
         DC.B                        -1,'Drive not ready',0
err_03s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Unbekanntes Kommando',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Commande inconnue',0
         DC.B                        -1,'Unknown command',0
err_04s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'CRC- Fehler',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Erreur CRC',0
         DC.B                        -1,'CRC error',0
err_05s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Kommando falsch',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Commande incorrecte',0
         DC.B                        -1,'Wrong command',0
err_06s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Spur nicht gefunden',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Piste introuvable',0
         DC.B                        -1,'Track not found',0
err_07s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Unbekanntes Medium',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'M',$82,'dia inconnu',0
         DC.B                        -1,'Unknown medium',0
err_08s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Sektor nicht gefunden',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Secteur introuvable',0
         DC.B                        -1,'Sector not found',0
err_09s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Kein Papier',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Pas de papier',0
         DC.B                        -1,'No paper',0
err_10s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Schreibfehler',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Erreur d',$27,'',$82,'criture',0
         DC.B                        -1,'Write error',0
err_11s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Lesefehler',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Erreur de lecture',0
         DC.B                        -1,'Read error',0
err_13s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Disk schreibgesch',$81,'tzt',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Disque en lecture seule',0
         DC.B                        -1,'Disk write-protected',0
err_14s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Unerlaubter Diskwechsel',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Changement de disque non autoris',$82,'',0
         DC.B                        -1,'Forbidden disk change',0
err_15s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Unbekanntes Ger',$84,'t',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'P',$82,'riph',$82,'rique inconnu',0
         DC.B                        -1,'Unknown device',0
err_16s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Defekte Sektoren',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Secteurs d',$82,'fectueux',0
         DC.B                        -1,'Defect sectors',0
err_17s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Andere Disk einlegen!',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Ins',$82,'rez un autre disque!',0
         DC.B                        -1,'Insert other disk!',0

err_32s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ung',$81,'ltige Funktionsnummer',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Num',$82,'ro de fonction invalide',0
         DC.B                        -1,'Invalid function number',0
err_33s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Datei nicht gefunden',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Fichier introuvable',0
         DC.B                        -1,'File not found',0
err_34s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Pfad nicht gefunden',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Chemin introuvable',0
         DC.B                        -1,'Path not found',0
err_35s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Zuviele ge',$94,'ffnete Dateien',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Trop de fichiers ouverts',0
         DC.B                        -1,'Too many open files',0
err_36s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Zugriff unm',$94,'glich',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Acc',$8a,'s impossible',0
         DC.B                        -1,'Access denied',0
err_37s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ung',$81,'ltiges Handle',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Handle non valide',0
         DC.B                        -1,'Invalid handle',0
err_39s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Zuwenig Speicher',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'M',$82,'moire insuffisante',0
         DC.B                        -1,'Out of memory',0
err_40s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ung',$81,'ltiger Speicherblock',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Bloc m',$82,'moire non valide',0
         DC.B                        -1,'Invalid memory block',0
err_46s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ung',$81,'ltiges Laufwerk',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Lecteur non valide',0
         DC.B                        -1,'Invalid drive',0
err_48s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Nicht dasselbe Laufwerk',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Lecteur diff',$82,'rent',0
         DC.B                        -1,'Not the same volume',0
err_49s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Keine weiteren Dateien',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Aucun autre fichier',0
         DC.B                        -1,'No more files',0
err_64s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Falscher Bereich',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Zone incorrecte',0
         DC.B                        -1,'Invalid range',0
err_65s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Interner Fehler',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Erreur interne',0
         DC.B                        -1,'Internal error',0
err_66s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Datei nicht ausf',$81,'hrbar',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Fichier non ex',$82,'cutable',0
         DC.B                        -1,'File not executable',0
err_67s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Mshrink- Fehler',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Erreur Mshrink',0
         DC.B                        -1,'Mshrink failure',0
err_69s: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'68000 Exception',0           * KAOS
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Exception 68000',0
         DC.B                        -1,'68000 Exception',0
toserrs: DC.B  COUNTRY_DE,COUNTRY_SG,-1,'TOS Fehler',0
         DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Erreur TOS',0
         DC.B                        -1,'TOS error',0

     IFEQ MAGIX
change_s:               DC.B COUNTRY_DE,COUNTRY_SG,-1,'Bitte Disk %: in Laufwerk A: einlegen!',0
                        DC.B COUNTRY_FR,COUNTRY_SF,-1,'Veuillez ins',$82,'rer le disque %: dans le lecteur A:!',0
                        DC.B                       -1,'Insert disk %: to drive A:!',0
diskerr_s:              DC.B COUNTRY_DE,COUNTRY_SG,-1,'  auf Laufwerk %:',CR,LF
                        DC.B                          '[A]bbruch, [W]iederholen, [I]gnorieren ?',0
                        DC.B COUNTRY_FR,COUNTRY_SF,-1,'  sur le disque %:',$d,$a
                        DC.B                          '[A]nnuler, [R]ecommencer, [I]gnorer ?',0
                        DC.B                       -1,'  on drive %:',CR,LF
                        DC.B                          '[A]bort, [R]etry, [I]gnore ?',0
     ENDC

out_of_envs:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Environment voll',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Environnement plein',CR,LF,0
                        DC.B                        -1,CR,LF,'Environment full',CR,LF,0
syntaxfehlers:          DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Syntax: SET [var=[wert]]',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Syntaxe: SET [var=[valeur]]',CR,LF,0
                        DC.B                        -1,CR,LF,'Syntax: SET [var=[value]]',CR,LF,0
disk_in_lw_s:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,' Disk in Laufwerk % ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Le disque dans le lecteur % ',0
                        DC.B                        -1,CR,LF,' Disk in drive % ',0
keinname_s:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,'hat keinen Namen',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'a pas de nom',0
                        DC.B                        -1,'is unnamed',0
ist_s:                  DC.B  COUNTRY_DE,COUNTRY_SG,-1,'ist ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'est ',0
                        DC.B                        -1,'is ',0
syntaxattrs:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Syntax: ATTRIB [[+|-]{rash}] datei(en)',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Syntaxe: ATTRIB [[+|-]{rash}] fichier(s)',CR,LF,0
                        DC.B                        -1,'Syntax: ATTRIB [[+|-]{rash}] file(s)',CR,LF,0
pfadzutiefs:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Pfad zu tief',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Chemin trop profond',CR,LF,0
                        DC.B                        -1,CR,LF,'Path too deep',CR,LF,0
pfads:                  DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Pfad: ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Chemin: ',0
                        DC.B                        -1,CR,LF,'Path: ',0
kbinsg_s:               DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  KB insgesamt verf',$81,'gbar',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  KO disponibles au total',CR,LF,0
                        DC.B                        -1,'  KB total available',CR,LF,0
bytes_in_s:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  Bytes in ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  Octets dans ',0
                        DC.B                        -1,'  bytes in ',0
hauptsp_s:              DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  Bytes Hauptspeicher',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  Octets m',$82,'moire principale',CR,LF,0
                        DC.B                        -1,'  bytes RAM',CR,LF,0
nbytesvers:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,' versteckten/System- Datei(en)',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' Fichier(s) cach',$82,'(s)/syst',$8a,'me',CR,LF,0
                        DC.B                        -1,' hidden or system file(s)',CR,LF,0
nbytesbens:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,' Benutzerdatei(en)',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' Fichier(s) utilisateur',CR,LF,0
                        DC.B                        -1,' user file(s)',CR,LF,0
nverzeichns:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  Verzeichnis(sse)',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  R',$82,'pertoire(s)',CR,LF,0
                        DC.B                        -1,'  directory/ies',CR,LF,0
zeile_gekuerzt_s:       DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Kommandozeile gek',$81,'rzt',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Ligne de commande tronqu',$82,'e',CR,LF,0
                        DC.B                        -1,CR,LF,'Command line truncated',CR,LF,0
nbytesfreis:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  Bytes frei',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  Octets libres',CR,LF,0
                        DC.B                        -1,'  bytes free',CR,LF,0
nkbfree:                DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  KB frei',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  KO libres',CR,LF,0
                        DC.B                        -1,'  KB free',CR,LF,0
nmbfree:                DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  MB frei',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  MO libres',CR,LF,0
                        DC.B                        -1,'  MB free',CR,LF,0
rens:                   DC.B  COUNTRY_DE,COUNTRY_SG,-1,'MV ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'MV ',0
                        DC.B                        -1,'MV ',0
err_rens:               DC.B  COUNTRY_DE,COUNTRY_SG,-1,' => Fehler : ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' => Erreur : ',0
                        DC.B                        -1,' => Error : ',0
isidents:               DC.B  COUNTRY_DE,COUNTRY_SG,-1,' Quelle und Ziel identisch',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' Source et destination identiques',CR,LF,0
                        DC.B                        -1,' Source is same as destination',CR,LF,0
copys:                  DC.B  COUNTRY_DE,COUNTRY_SG,-1,'COPY ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'COPY ',0
                        DC.B                        -1,'COPY ',0
auf_s:                  DC.B  COUNTRY_DE,COUNTRY_SG,-1,' auf ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' sur ',0
                        DC.B                        -1,' on ',0
zielvolls:              DC.B  COUNTRY_DE,COUNTRY_SG,-1,' Zieldisk voll',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' Disque de destination plein',CR,LF,0
                        DC.B                        -1,' Destination volume full',CR,LF,0
syntaxrens:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Syntax: MV Quelle Ziel',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Syntaxe: MV Source Destination',CR,LF,0
                        DC.B                        -1,'Syntax: MV source destination',CR,LF,0
syntaxcopys:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Syntax: COPY [-t] Quelle Ziel',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Syntaxe: COPY [-t] Source Destination',CR,LF,0
                        DC.B                        -1,'Syntax: COPY [-t] source destination',CR,LF,0
unerlcopy_s:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ung',$81,'ltiges COPY',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'COPY invalide',CR,LF,0
                        DC.B                        -1,'Invalid COPY',CR,LF,0
unerlren_s:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ung',$81,'ltiges MV',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'MV invalide',CR,LF,0
                        DC.B                        -1,'Invalid MV',CR,LF,0
ndateiens:              DC.B  COUNTRY_DE,COUNTRY_SG,-1,' Datei(en) kopiert',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' Fichier(s) copi',CR,LF,0
                        DC.B                        -1,' file(s) copied',CR,LF,0
akt_date_is:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Aktuelles Datum ist ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'La date actuelle est ',0
                        DC.B                        -1,CR,LF,'Current date is ',0
give_dates:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Neues Datum (tt/mm/jj) : ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Nouvelle date (jj/mm/aa) : ',0
                        DC.B                        -1,CR,LF,'New date (dd/mm/yy) : ',0
akt_time_is:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Aktuelle Zeit ist ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'L',$27,'heure actuelle est ',0
                        DC.B                        -1,CR,LF,'Current time is ',0
give_times:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Neue Zeit (hh:mm:ss) : ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Nouvelle heure (hh:mm:ss) : ',0
                        DC.B                        -1,CR,LF,'New time (hh:mm:ss) : ',0
falsches_forms:         DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Falsches Format',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Format incorrect',CR,LF,0
                        DC.B                        -1,CR,LF,'Wrong format',CR,LF,0
loesch_s:               DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'L',$94,'sche ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Effacer ',0
                        DC.B                        -1,CR,LF,'Delete ',0
auswahl_s:              DC.B  COUNTRY_DE,COUNTRY_SG,-1,' (J/N/G/A) ? ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' (O/N/G/A) ? ',0
                        DC.B                        -1,' (Y/N/G/A) ? ',0
global_s:               DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Global',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Global',0
                        DC.B                        -1,'Global',0
nein_s:                 DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Nein',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Non',0
                        DC.B                        -1,'No',0
ja_s:                   DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ja',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Oui',0
                        DC.B                        -1,'Yes',0
quit_s:                 DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Abbruch',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Annuler',0
                        DC.B                        -1,'Abort',0
dels:                   DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'DEL ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'DEL ',0
                        DC.B                        -1,CR,LF,'DEL ',0
syntax_dels:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Syntax: DEL [-n] datei1 ...',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Syntaxe: DEL [-n] fichier1 ...',CR,LF,0
                        DC.B                        -1,CR,LF,'Syntax: DEL [-n] file1 ...',CR,LF,0
space3_s:               DC.B  '   ',0
dir_zeichens:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,'   <DIR>',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'   <DIR>',0
                        DC.B                        -1,'   <DIR>',0
verzchn_vons:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,' Verzeichnis von ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' R',$82,'pertoire de ',0
                        DC.B                        -1,' Content of ',0
n_dbytes:               DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  Bytes in',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  Octets dans',0
                        DC.B                        -1,'  bytes in',0
n_dateiens:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,' Datei(en)',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' fichier(s)',0
                        DC.B                        -1,' file(s)',0
echo_ists:              DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'ECHO ist ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'ECHO est ',0
                        DC.B                        -1,CR,LF,'ECHO is ',0
rmd_syntaxs:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Syntax: MD/RD Verzeichnis',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Syntaxe: MD/RD R',$82,'pertoire',CR,LF,0
                        DC.B                        -1,CR,LF,'Syntax: MD/RD directory',CR,LF,0
ren_syntaxs:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Syntax: REN Quelle Name',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Syntaxe: REN Source Nom',CR,LF,0
                        DC.B                        -1,CR,LF,'Syntax: REN source name',CR,LF,0
kein_pfads:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Kein Pfad',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Aucun chemin',0
                        DC.B                        -1,'No path',0
datei_s:                DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Datei: ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Fichier: ',0
                        DC.B                        -1,CR,LF,'file: ',0
kann_s:                 DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Kann ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Ouverture de ',0
                        DC.B                        -1,CR,LF,'Cannot open ',0
nicht_offn_s:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,' nicht ',$94,'ffnen',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' impossible',CR,LF,0
                        DC.B                        -1,' ',CR,LF,0
syntax_ts:              DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Syntax: TYPE|TOUCH datei1 ...',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Syntaxe: TYPE|TOUCH Nom(s) de fichier',CR,LF,0
                        DC.B                        -1,CR,LF,'Syntax: TYPE|TOUCH filename(s)',CR,LF,0
status_s:               DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Flag ist ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Le Flag est ',0
                        DC.B                        -1,CR,LF,'Flag is ',0
error_verifys:          DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Ung',$81,'ltiger Zustand',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Etat invalide',CR,LF,0
                        DC.B                        -1,'Invalid state',CR,LF,0
syntax_sorts:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Syntax: SORT -C -R -n',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Syntaxe: SORT -C -R -n',CR,LF,0
                        DC.B                        -1,CR,LF,'Syntax: SORT -C -R -n',CR,LF,0
sort_memerrs:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'SORT: Zuwenig Speicher',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'SORT: M',$82,'moire insuffisante',CR,LF,0
                        DC.B                        -1,CR,LF,'SORT: insufficient memory',CR,LF,0
sort_zielvolls:         DC.B  COUNTRY_DE,COUNTRY_SG,-1,'SORT: Ziel-Volume voll',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'SORT: Disque destination plein',CR,LF,0
                        DC.B                        -1,'SORT: Destination volume full',CR,LF,0
syntax_finds:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Syntax: FIND text',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Syntaxe: FIND cha',$8c,'ne',CR,LF,0
                        DC.B                        -1,CR,LF,'Syntax: FIND string',CR,LF,0
mehrs:                  DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,'--Mehr--',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,'--Plus--',0
                        DC.B                        -1,CR,'--more--',0
syntax_ifs:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Fehler in IF- Ausdruck',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Erreur d',$27,'expression IF',CR,LF,0
                        DC.B                        -1,CR,LF,'Error in IF expression',CR,LF,0
syntax_shifts:          DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'SHIFT: Operand fehlt',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'SHIFT: Op',$82,'rande manquante',CR,LF,0
                        DC.B                        -1,CR,LF,'SHIFT: missing operand',CR,LF,0
lbl_not_found_s:        DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'GOTO: Label nicht gefunden',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'GOTO: Balise non trouv',$82,'e',CR,LF,0
                        DC.B                        -1,CR,LF,'GOTO: label not found',CR,LF,0
for_error_s:            DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'FOR: Syntaxfehler oder Schachtelung',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'FOR: Erreur de syntaxe ou d',$27,'imbrication',CR,LF,0
                        DC.B                        -1,CR,LF,'FOR: syntax error or nesting',CR,LF,0
pipe_errs:              DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,' Pipe- Fehler',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,' Erreur de Pipe',0
                        DC.B                        -1,CR,LF,' Pipe error',0
redir_errs:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,' Fehler beim Umlenken von STD',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,' Erreur lors de la redirection de STD',0
                        DC.B                        -1,CR,LF,' Error while redirecting STD',0
batch_errs:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'BATCH zu tief verschachtelt',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'BATCH trop imbriqu',$82,'',CR,LF,0
                        DC.B                        -1,CR,LF,'BATCH nesting overflow',CR,LF,0
exec_fehler1_s:         DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'EXEC Fehler =>',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Erreur EXEC =>',0
                        DC.B                        -1,CR,LF,'EXEC error =>',0
exec_fehler2_s:         DC.B  COUNTRY_DE,COUNTRY_SG,-1,'<=',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'<=',CR,LF,0
                        DC.B                        -1,'<=',CR,LF,0
pfad_ueberl_s:          DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Pfad',$81,'berlauf',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'D',$82,'bordement de chemin',0
                        DC.B                        -1,CR,LF,'Path overflow',0
kmd_nicht_gef_s:        DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,'Kommando nicht gefunden',CR,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,'Commande introuvable',CR,LF,0
                        DC.B                        -1,CR,LF,'Command not found',CR,LF,0
nach_art_s:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,' nach Art',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' par type',0
                        DC.B                        -1,' by date/time',0
nach_dat_s:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,' nach Datum',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' par date',0
                        DC.B                        -1,' by size',0
nach_grs_s:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,' nach Gr',$94,$9e,'e',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' par taille',0
                        DC.B                        -1,' unsorted',0
nach_nix_s:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,' unsortiert',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' pon tri',$82,'  ',0
                        DC.B                        -1,' bytes free',CR,LF,LF,0
bytes_free_s:           DC.B  COUNTRY_DE,COUNTRY_SG,-1,' Bytes frei',CR,LF,LF,0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,' Octets libres',CR,LF,LF,0
                        DC.B                        -1,' bytes free',CR,LF,LF,0
taste_drueckens:        DC.B  COUNTRY_DE,COUNTRY_SG,-1,'Taste dr',$81,'cken ',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'Pressez une touche ',0
                        DC.B                        -1,'Press key ',0
not_founds:             DC.B  COUNTRY_DE,COUNTRY_SG,-1,'  nicht gefunden'
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,'  introuvable'
                        DC.B                        -1,'  not found'
keine_dateiens:         DC.B  COUNTRY_DE,COUNTRY_SG,-1,CR,LF,' Keine Dateien',0
                        DC.B  COUNTRY_FR,COUNTRY_SF,-1,CR,LF,' Aucun fichier',0
                        DC.B                        -1,CR,LF,' No files',0


          EVEN
