FNTS_CREATE			EQU	180
FNTS_DELETE			EQU	181
FNTS_OPEN			EQU	182
FNTS_CLOSE			EQU	183
FNTS_GET				EQU	184
FNTS_SET				EQU	185
FNTS_EVNT			EQU	186
FNTS_DO				EQU	187

FNTS_GET_NO_STYLES	EQU	0
FNTS_GET_STYLE		EQU	1
FNTS_GET_NAME		EQU	2
FNTS_GET_INFO		EQU	3

FNTS_ADD				EQU	0
FNTS_REMOVE			EQU	1
