/* Resource Datei Indizes fÅr MAGXDESL */

#define HAUPTMEN         0   /* Menuebaum */
#define MM_DESK          3   /* TITLE in Baum HAUPTMEN */
#define MM_DATEI         4   /* TITLE in Baum HAUPTMEN */
#define MM_ANZEI         5   /* TITLE in Baum HAUPTMEN */
#define MM_OPTIO         6   /* TITLE in Baum HAUPTMEN */
#define MM_OBJS          7   /* TITLE in Baum HAUPTMEN */
#define MM_SMODE         8   /* STRING in Baum HAUPTMEN */
#define M_ABOUT          11  /* STRING in Baum HAUPTMEN */
#define M_OPEN           20  /* STRING in Baum HAUPTMEN */
#define M_INFO           21  /* STRING in Baum HAUPTMEN */
#define M_LOESCH         22  /* STRING in Baum HAUPTMEN */
#define M_NEUORD         24  /* STRING in Baum HAUPTMEN */
#define M_SEARCH         25  /* STRING in Baum HAUPTMEN */
#define M_SCHL           26  /* STRING in Baum HAUPTMEN */
#define M_SCHLFN         27  /* STRING in Baum HAUPTMEN */
#define M_SELALL         28  /* STRING in Baum HAUPTMEN */
#define M_FORMAT         30  /* STRING in Baum HAUPTMEN */
#define M_EJECT          31  /* STRING in Baum HAUPTMEN */
#define M_DCOPY          32  /* STRING in Baum HAUPTMEN */
#define M_ABILDR         34  /* STRING in Baum HAUPTMEN */
#define M_ATEXT          35  /* STRING in Baum HAUPTMEN */
#define M_FONT           37  /* STRING in Baum HAUPTMEN */
#define M_SPALTN         38  /* STRING in Baum HAUPTMEN */
#define M_ZGROES         39  /* STRING in Baum HAUPTMEN */
#define M_ZDATUM         40  /* STRING in Baum HAUPTMEN */
#define M_ZZEIT          41  /* STRING in Baum HAUPTMEN */
#define M_SNAME          43  /* STRING in Baum HAUPTMEN */
#define M_SDATUM         44  /* STRING in Baum HAUPTMEN */
#define M_SGROES         45  /* STRING in Baum HAUPTMEN */
#define M_STYP           46  /* STRING in Baum HAUPTMEN */
#define M_SNICHT         47  /* STRING in Baum HAUPTMEN */
#define M_MASKE          49  /* STRING in Baum HAUPTMEN */
#define M_LAUFWE         51  /* STRING in Baum HAUPTMEN */
#define M_ANWNDG         52  /* STRING in Baum HAUPTMEN */
#define M_ICASGN         53  /* STRING in Baum HAUPTMEN */
#define M_EINSTE         55  /* STRING in Baum HAUPTMEN */
#define M_CHGRES         56  /* STRING in Baum HAUPTMEN */
#define M_ARBSIC         57  /* STRING in Baum HAUPTMEN */
#define M_ENDE           59  /* STRING in Baum HAUPTMEN */
#define M_OBJPAR         60  /* BOX in Baum HAUPTMEN */
#define M_WIND1          61  /* STRING in Baum HAUPTMEN */
#define M_WIND2          62  /* STRING in Baum HAUPTMEN */
#define M_WIND3          63  /* STRING in Baum HAUPTMEN */
#define M_WIND4          64  /* STRING in Baum HAUPTMEN */
#define M_WIND5          65  /* STRING in Baum HAUPTMEN */
#define M_WIND6          66  /* STRING in Baum HAUPTMEN */
#define M_TRENN          67  /* STRING in Baum HAUPTMEN */
#define M_PGM1           68  /* STRING in Baum HAUPTMEN */
#define M_PGM2           69  /* STRING in Baum HAUPTMEN */
#define M_PGM3           70  /* STRING in Baum HAUPTMEN */
#define M_PGM4           71  /* STRING in Baum HAUPTMEN */
#define M_PGM5           72  /* STRING in Baum HAUPTMEN */
#define M_PGM6           73  /* STRING in Baum HAUPTMEN */
#define M_PGM7           74  /* STRING in Baum HAUPTMEN */
#define M_PGM8           75  /* STRING in Baum HAUPTMEN */
#define M_PGM9           76  /* STRING in Baum HAUPTMEN */
#define M_PGM10          77  /* STRING in Baum HAUPTMEN */
