; Country- Codes laut Atari Doku
COUNTRY_US      EQU   0           ; USA
COUNTRY_DE      EQU   1           ; Germany
COUNTRY_FR      EQU   2           ; France
COUNTRY_UK      EQU   3           ; United Kingdom
COUNTRY_ES      EQU   4           ; Spain
COUNTRY_IT      EQU   5           ; Italy
COUNTRY_SE      EQU   6           ; Sweden
COUNTRY_SF      EQU   7           ; Switzerland (french)
COUNTRY_SG      EQU   8           ; Switzerland (german)
COUNTRY_TR      EQU   9           ; Turkey
COUNTRY_FI      EQU   10          ; Finland
COUNTRY_NO      EQU   11          ; Norway
COUNTRY_DK      EQU   12          ; Denmark
COUNTRY_SA      EQU   13          ; Saudi Arabia
COUNTRY_NL      EQU   14          ; Netherlands
COUNTRY_CZ      equ   15          ; Czech Republic COUNTRY_HU      equ   16          ; Hungary
