
;
; Seedfill
; Folgende Var. urspruenglich ab $181c
; v_1c equ 0
v_1e                    EQU 2           ;.l Farbwert
v_2c                    EQU 6
v_2e                    EQU 8
v_30                    EQU 10
v_32                    EQU 12
v_34                    EQU 14
v_36                    EQU 16
v_38                    EQU 18
v_3a                    EQU 20
v_3c                    EQU 22
v_3e                    EQU 24
v_40                    EQU 26
v_42                    EQU 28
v_44                    EQU 30
v_46                    EQU 32
v_48                    EQU 34
v_4a                    EQU 36
