/* Resource Datei Indizes fÅr FSELX */

#define FSEL             0   /* Formular/Dialog */
#define POS_BOX          1   /* IBOX in Baum FSEL */
#define NAM_LABEL        2   /* STRING in Baum FSEL */
#define FPT_USER         3   /* FTEXT in Baum FSEL */
#define FS_ICONBACK      4   /* USERDEF in Baum FSEL */
#define FS_DRIVE         5   /* BUTTON in Baum FSEL */
#define FS_PATH          6   /* BUTTON in Baum FSEL */
#define FS_EXTENSION     7   /* BUTTON in Baum FSEL */
#define FS_BBOX          8   /* IBOX in Baum FSEL */
#define FS_BOX0          9   /* BOX in Baum FSEL */
#define ON_CLIP0         10  /* USERDEF in Baum FSEL */
#define FS_ICON0         11  /* BOX in Baum FSEL */
#define FS_STRING0       12  /* STRING in Baum FSEL */
#define OFF_CLIP0        13  /* USERDEF in Baum FSEL */
#define FS_BOX1          14  /* BOX in Baum FSEL */
#define ON_CLIP1         15  /* USERDEF in Baum FSEL */
#define FS_ICON1         16  /* BOX in Baum FSEL */
#define FS_STRING1       17  /* STRING in Baum FSEL */
#define OFF_CLIP1        18  /* USERDEF in Baum FSEL */
#define FS_BOX2          19  /* BOX in Baum FSEL */
#define ON_CLIP2         20  /* USERDEF in Baum FSEL */
#define FS_ICON2         21  /* BOX in Baum FSEL */
#define FS_STRING2       22  /* STRING in Baum FSEL */
#define OFF_CLIP2        23  /* USERDEF in Baum FSEL */
#define FS_BOX3          24  /* BOX in Baum FSEL */
#define ON_CLIP3         25  /* USERDEF in Baum FSEL */
#define FS_ICON3         26  /* BOX in Baum FSEL */
#define FS_STRING3       27  /* STRING in Baum FSEL */
#define OFF_CLIP3        28  /* USERDEF in Baum FSEL */
#define FS_BOX4          29  /* BOX in Baum FSEL */
#define ON_CLIP4         30  /* USERDEF in Baum FSEL */
#define FS_ICON4         31  /* BOX in Baum FSEL */
#define FS_STRING4       32  /* STRING in Baum FSEL */
#define OFF_CLIP4        33  /* USERDEF in Baum FSEL */
#define FS_BOX5          34  /* BOX in Baum FSEL */
#define ON_CLIP5         35  /* USERDEF in Baum FSEL */
#define FS_ICON5         36  /* BOX in Baum FSEL */
#define FS_STRING5       37  /* STRING in Baum FSEL */
#define OFF_CLIP5        38  /* USERDEF in Baum FSEL */
#define FS_BOX6          39  /* BOX in Baum FSEL */
#define ON_CLIP6         40  /* USERDEF in Baum FSEL */
#define FS_ICON6         41  /* BOX in Baum FSEL */
#define FS_STRING6       42  /* STRING in Baum FSEL */
#define OFF_CLIP6        43  /* USERDEF in Baum FSEL */
#define FS_BOX7          44  /* BOX in Baum FSEL */
#define ON_CLIP7         45  /* USERDEF in Baum FSEL */
#define FS_ICON7         46  /* BOX in Baum FSEL */
#define FS_STRING7       47  /* STRING in Baum FSEL */
#define OFF_CLIP7        48  /* USERDEF in Baum FSEL */
#define FS_BOX8          49  /* BOX in Baum FSEL */
#define ON_CLIP8         50  /* USERDEF in Baum FSEL */
#define FS_ICON8         51  /* BOX in Baum FSEL */
#define FS_STRING8       52  /* STRING in Baum FSEL */
#define OFF_CLIP8        53  /* USERDEF in Baum FSEL */
#define FS_BOX9          54  /* BOX in Baum FSEL */
#define ON_CLIP9         55  /* USERDEF in Baum FSEL */
#define FS_ICON9         56  /* BOX in Baum FSEL */
#define FS_STRING9       57  /* STRING in Baum FSEL */
#define OFF_CLIP9        58  /* USERDEF in Baum FSEL */
#define FS_BOX10         59  /* BOX in Baum FSEL */
#define ON_CLIP10        60  /* USERDEF in Baum FSEL */
#define FS_ICON10        61  /* BOX in Baum FSEL */
#define FS_STRING10      62  /* STRING in Baum FSEL */
#define OFF_CLIP10       63  /* USERDEF in Baum FSEL */
#define FS_BOX11         64  /* BOX in Baum FSEL */
#define ON_CLIP11        65  /* USERDEF in Baum FSEL */
#define FS_ICON11        66  /* BOX in Baum FSEL */
#define FS_STRING11      67  /* STRING in Baum FSEL */
#define OFF_CLIP11       68  /* USERDEF in Baum FSEL */
#define FS_BOX12         69  /* BOX in Baum FSEL */
#define ON_CLIP12        70  /* USERDEF in Baum FSEL */
#define FS_ICON12        71  /* BOX in Baum FSEL */
#define FS_STRING12      72  /* STRING in Baum FSEL */
#define OFF_CLIP12       73  /* USERDEF in Baum FSEL */
#define FS_BOX13         74  /* BOX in Baum FSEL */
#define ON_CLIP13        75  /* USERDEF in Baum FSEL */
#define FS_ICON13        76  /* BOX in Baum FSEL */
#define FS_STRING13      77  /* STRING in Baum FSEL */
#define OFF_CLIP13       78  /* USERDEF in Baum FSEL */
#define FS_UP            79  /* BOXCHAR in Baum FSEL */
#define FS_UDBACK        80  /* BOX in Baum FSEL */
#define FS_UDSL          81  /* BOX in Baum FSEL */
#define FS_DOWN          82  /* BOXCHAR in Baum FSEL */
#define FS_LEFT          83  /* BOXCHAR in Baum FSEL */
#define FS_LRBACK        84  /* BOX in Baum FSEL */
#define FS_LRSL          85  /* BOX in Baum FSEL */
#define FS_RIGHT         86  /* BOXCHAR in Baum FSEL */
#define FS_OK            87  /* BUTTON in Baum FSEL */
#define FS_CANCEL        88  /* BUTTON in Baum FSEL */
#define OPTIONS          89  /* BUTTON in Baum FSEL */
#define FS_INPUT_EXT     90  /* FBOXTEXT in Baum FSEL */
#define TITLE            91  /* STRING in Baum FSEL */
#define FS_SIZER         92  /* IMAGE in Baum FSEL */

#define FSEL_ICONS       1   /* Formular/Dialog */
#define FS_ICFOLDER      1   /* USERDEF in Baum FSEL_ICONS */

#define SORT_POPUP       2   /* Formular/Dialog */
#define SORT_NAME        1   /* STRING in Baum SORT_POPUP */
#define SORT_DATE        2   /* STRING in Baum SORT_POPUP */
#define SORT_SIZE        3   /* STRING in Baum SORT_POPUP */
#define SORT_TYP         4   /* STRING in Baum SORT_POPUP */
#define SORT_UNSORT      5   /* STRING in Baum SORT_POPUP */
