/*
 * output values for v_opnwk/vq_extnd
 */

work_out0:        DC.W 0                  /* 0  Maximum addressable width */
                  DC.W 0                  /* 1  Maximum addressable height */
                  DC.W 0                  /* 2  Scalability flag */
                  DC.W 0                  /* 3  Pixel width in microns */
                  DC.W 0                  /* 4  Pixel height in microns */
                  DC.W 3                  /* 5  number of character heights */
                  DC.W 7                  /* 6  number of line types */
                  DC.W 0                  /* 7  number of line widths */
                  DC.W 6                  /* 8  number of marker types */
                  DC.W 0                  /* 9  number of marker heights */
                  DC.W 1                  /* 10 number of accessible fonts */
                  DC.W 24                 /* 11 number of patterns */
                  DC.W 12                 /* 12 number of hatch styles */
                  DC.W 0                  /* 13 number of simultaneously depicted colors */
                  DC.W 10                 /* 14 number of GDPs */
                  DC.W 1                  /* 15 GDP: bar */
                  DC.W 2                  /* 16 GDP: arc */
                  DC.W 3                  /* 17 GDP: pieslice */
                  DC.W 4                  /* 18 GDP: circle */
                  DC.W 5                  /* 19 GDP: ellipse */
                  DC.W 6                  /* 20 GDP: elliptical arc */
                  DC.W 7                  /* 21 GDP: elliptical pie */
                  DC.W 8                  /* 22 GDP: rounded box */
                  DC.W 9                  /* 23 GDP: filled rounded box */
                  DC.W 10                 /* 24 GDP: justified text */
                  DC.W 3                  /* 25 attributes bar */
                  DC.W 0                  /* 26 attributes arc */
                  DC.W 3                  /* 27 attributes pieslice */
                  DC.W 3                  /* 28 attributes circle */
                  DC.W 3                  /* 29 attributes ellipse */
                  DC.W 0                  /* 30 attributes elliptical arc */
                  DC.W 3                  /* 31 attributes elliptical pie */
                  DC.W 0                  /* 32 attributes rounded box */
                  DC.W 3                  /* 33 attributes filled rounded box */
                  DC.W 2                  /* 34 attributes justified text */
                  DC.W 1                  /* 35 color available */
                  DC.W 1                  /* 36 text rotation available */
                  DC.W 1                  /* 37 fill area available */
                  DC.W 0                  /* 38 cellarray not available */
                  DC.W 0                  /* 39 number of color levels available */
                  DC.W 2                  /* 40 locator available for keyboard and mouse */
                  DC.W 1                  /* 41 valuator available for keyboard */
                  DC.W 1                  /* 42 choice available for keyboard */
                  DC.W 1                  /* 43 string available for keyboard */
                  DC.W 2                  /* 44 device type input/output */
                  DC.W 5                  /* 45 Minimum character width  */
                  DC.W 4                  /* 46 Minimum character height  */
                  DC.W 7                  /* 47 Maximum character width */
                  DC.W 13                 /* 48 Maximum character height */
                  DC.W L_WIDTH_MIN        /* 49 Minimum representable line width */
                  DC.W 0                  /* 50 */
                  DC.W L_WIDTH_MAX        /* 51 Maximum line width */
                  DC.W 0                  /* 52 */
                  DC.W M_WIDTH_MIN        /* 53 Minimum marker width */
                  DC.W M_HEIGHT_MIN       /* 54 Minimum marker height */
                  DC.W M_WIDTH_MAX        /* 55 Maximum marker width */
                  DC.W M_HEIGHT_MAX       /* 56 Maximum marker height */

extnd_out0:       DC.W 4                  /* 0  Common alpha and graphic controller with shared video memory */
                  DC.W 0                  /* 1  number of color levels */
                  DC.W 31                 /* 2  supported text effects */
                  DC.W 0                  /* 3  raster scaling impossible */
                  DC.W 0                  /* 4  number of planes */
                  DC.W 1                  /* 5  CLUT exists */
                  DC.W 2200               /* 6  performance factor */
                  DC.W 1                  /* 7  contour fill capability */
                  DC.W 2                  /* 8  text rotation in steps of 1/10 degrees */
                  DC.W 4                  /* 9  number of writing modes available */
                  DC.W 2                  /* 10 highest available input mode */
                  DC.W 1                  /* 11 text alignment possible */
                  DC.W 0                  /* 12 device cannot ink */
                  DC.W 0                  /* 13 no rubberbanding */
                  DC.W MAX_PTS            /* 14 maximum number of input vertices */
                  DC.W -1                 /* 15 intin unlimited */
                  DC.W 2                  /* 16 number of mouse buttons */
                  DC.W 0                  /* 17 line types not avaiable for wide lines */
                  DC.W 4                  /* 18 writing modes available for wide lines */
                  DC.W 0,0,0,0,0,0,0,0
                  DC.W 0,0,0,0,0,0,0,0
                  DC.W 0,0,0,0,0,0,0,0
                  DC.W 0,0,0,0,0,0,0,0
                  DC.W 0,0,0,0,0,0,0,0
