	.OFFSET 0

	ds.b 58
cxs_line_width:     ds.w 1 /*  58 */
cxs_xres:           ds.w 1 /*  60 */
cxs_yres:           ds.w 1 /*  62 */
cxs_64:             ds.w 1 /*  64 */
	ds.b 168
cxs_234:            ds.w 1 /* 234 */
cxs_236:            ds.w 1 /* 236 */
	ds.b 30
cxs_virtual:        ds.w 1 /* 268 */
	ds.b 4
cxs_274:            ds.l 1 /* 274 */
cxs_278:            ds.l 1 /* 278 */
cxs_282:            ds.l 1 /* 282 */
	ds.b 4
cxs_rgbtab:         ds.l 1 /* 290 */
	ds.b 66
cxs_360:            ds.l 1 /* 360 */
cxs_364:            ds.l 1 /* 364 */
	ds.b 4
cxs_372:            ds.l 1 /* 372 */
cxs_376:            ds.l 1 /* 376 */
	ds.b 8
cxs_388:            ds.l 1 /* 388 */
	ds.b 4
cxs_dac_type:       ds.w 1 /* 396 */
	ds.b 2
cxs_400:            ds.w 1 /* 400 */
	ds.b 26
cxs_428:            ds.w 1 /* 428 */
	ds.b 10
cxs_visible_xres:   ds.w 1 /* 440 */
cxs_visible_yres:   ds.w 1 /* 442 */
        ds.b 18
cxs_462:            ds.w 1 /* 462 */
