#!/bin/sh

set -e

srcdir="$PWD"

# LANGUAGES="de fr en"
# BUILDROOT="$PWD/build"

ROOTFS="$BUILDROOT/rootfs"
rm -rf "$ROOTFS"

cd "$BUILDROOT"

# MagicOnLinux expects all filenames in the root filesystem to be uppercase

find . -depth | while read i; do
	test "$i" = "." && continue
	d=`dirname $i`
	f="$d/"`basename $i | tr '[[:lower:]]' '[[:upper:]]'`
	if test "$f" != "$i"; then
		mv "$i" "$d/xxxx$$"
		mv "$d/xxxx$$" "$f"
	fi
done

mkdir -p "$ROOTFS/AUTO/ACCS/CPX"
mkdir -p "$ROOTFS/GEMSYS/HOME"
mkdir -p "$ROOTFS/GEMSYS/MAGIC/START"
mkdir -p "$ROOTFS/GEMSYS/MAGIC/STOP"
mkdir -p "$ROOTFS/GEMSYS/MAGIC/UTILITY"
mkdir -p "$ROOTFS/GEMSYS/MAGIC/XTENSION"
mkdir -p "$ROOTFS/GEMSYS/MAGIC/XTENSION/HIDE"
mkdir -p "$ROOTFS/GEMSYS/MAGIC/XTENSION/HIDE2"
mkdir -p "$ROOTFS/GEMSYS/MAGIC/XTENSION/THEMES"
mkdir -p "$ROOTFS/GEMSYS/GEMSCRAP"
mkdir -p "$ROOTFS/GEMSYS/GEMDESK"
mkdir -p "$ROOTFS/GEMSYS/GEMDESK/PAT"
mkdir -p "$ROOTFS/GEMSYS/GEMDESK/RSC"
mkdir -p "$ROOTFS/GEMSYS/GEMDESK/HELP"
mkdir -p "$ROOTFS/BIN"
mkdir -p "$ROOTFS/CLIPBRD"
mkdir -p "$ROOTFS/EXTRAS"
mkdir -p "$ROOTFS/EXTRAS/BIN"
mkdir -p "$ROOTFS/EXTRAS/FLOCK_OK"
mkdir -p "$ROOTFS/EXTRAS/CLOCK"
mkdir -p "$ROOTFS/EXTRAS/AES_LUPE"
mkdir -p "$ROOTFS/EXTRAS/MAGICCFG"
mkdir -p "$ROOTFS/EXTRAS/APPLINE"

#
# localizations
#
for lang in $LANGUAGES; do
	LANG_UPPER=$(echo $lang | tr 'a-z' 'A-Z')

	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/AUTO/ACCS/CPX"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/GEMSYS/GEMDESK"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/GEMSYS/GEMDESK/HELP"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/GEMSYS/MAGIC/XTENSION"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/EXTRAS"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/EXTRAS/FLOCK_OK"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/EXTRAS/AES_LUPE"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/EXTRAS/MAGICCFG"
	mkdir -p "$ROOTFS/LANG/$LANG_UPPER/EXTRAS/APPLINE"

	for f in \
		MAGICLIN.OS \
		GEMSYS/GEMDESK/APPLICAT.INF \
		GEMSYS/GEMDESK/APPLICAT.RSC \
		GEMSYS/GEMDESK/CHGRES.RSC \
		GEMSYS/GEMDESK/MAGXDESK.RSC \
		GEMSYS/GEMDESK/MGCOPY.RSC \
		GEMSYS/GEMDESK/MGEDIT.RSC \
		GEMSYS/GEMDESK/MGNOTICE.RSC \
		GEMSYS/GEMDESK/MGNOTICE.TXT \
		GEMSYS/GEMDESK/MGFORMAT.RSC \
		GEMSYS/GEMDESK/MGSEARCH.RSC \
		GEMSYS/GEMDESK/MOD_APP.TXT \
		GEMSYS/GEMDESK/VFATCONF.RSC \
		GEMSYS/GEMDESK/VT52.RSC \
		EXTRAS/MAGICCFG/MAGICCFG.RSC \
		EXTRAS/MAGICCFG/MAGICCFG.BGH \
		EXTRAS/MAGICCFG/MAGICCFG.TXT \
		EXTRAS/MAGICCFG/MAGICCFG.HYP \
		EXTRAS/FLOCK_OK/FLOCK_OK.TXT \
		EXTRAS/AES_LUPE/AES_LUPE.TXT \
		EXTRAS/APPLINE/APPLINE.RSC \
		EXTRAS/MAGX.INF \
		GEMSYS/MAGIC/XTENSION/PDLG.SLB \
	; do
		cp -a "$BUILDROOT/$LANG_UPPER/$f" "$ROOTFS/LANG/$LANG_UPPER/$f"
	done
	cp -a "$BUILDROOT/$LANG_UPPER/AUTO/ACCS/CPX/"*.CPX "$ROOTFS/LANG/$LANG_UPPER/AUTO/ACCS/CPX/"
	# TODO: english & french translation
	cp -a "$BUILDROOT/$LANG_UPPER/GEMSYS/GEMDESK/HELP/"*.HLP "$ROOTFS/LANG/$LANG_UPPER/GEMSYS/GEMDESK/HELP/"
done


#
# Common files
#
LANG_UPPER=EN
for f in \
	GEMSYS/HOME/COPS.INF \
	AUTO/ACCS/COPS.ACC \
	BIN/CRASHDMP.TOS \
	BIN/FC.TTP \
	BIN/LIMITMEM.TTP \
	BIN/MEMEXAMN.TTP \
	BIN/HELP.BAT \
	GEMSYS/GEMDESK/APPLICAT.APP \
	GEMSYS/GEMDESK/CHGRES.PRG \
	GEMSYS/GEMDESK/MAGXDESK.APP \
	GEMSYS/GEMDESK/MGCLOCK.PRG \
	GEMSYS/GEMDESK/MGCOPY.APP \
	GEMSYS/GEMDESK/MGEDIT.APP \
	GEMSYS/GEMDESK/MGFORMAT.PRG \
	GEMSYS/GEMDESK/MGNOTICE.APP \
	GEMSYS/GEMDESK/MGSEARCH.APP \
	GEMSYS/GEMDESK/MGVIEW.APP \
	GEMSYS/GEMDESK/MGXCLOCK.PRG \
	GEMSYS/GEMDESK/MOD_APP.TTP \
	GEMSYS/GEMDESK/SHOWFILE.TTP \
	GEMSYS/GEMDESK/SHOWFREE.TOS \
	GEMSYS/GEMDESK/SHUTDOWN.PRG \
	GEMSYS/GEMDESK/SHUTDOWN.INF \
	GEMSYS/GEMDESK/VFATCONF.PRG \
	GEMSYS/GEMDESK/VT52.PRG \
	GEMSYS/GEMDESK/MCMD.TOS \
	EXTRAS/MAGICCFG/MAGICCFG.APP \
	EXTRAS/MAGICCFG/HISTORY.TXT \
	EXTRAS/APPLINE/APPLINE.APP \
	EXTRAS/APPLINE/APPLINE.INF \
	GEMSYS/GEMDESK/WBDAEMON.PRG \
	GEMSYS/MAGIC/START/MMXDAEMN.PRX \
	GEMSYS/MAGIC/XTENSION/DEV_SER.DEV \
	GEMSYS/MAGIC/XTENSION/RAMDISK.XFX \
	GEMSYS/MAGIC/XTENSION/SPINMAGC.XFX \
	GEMSYS/MAGIC/XTENSION/EDITOBJC.SLB \
	GEMSYS/MAGIC/XTENSION/LOAD_IMG.SLB \
	GEMSYS/MAGIC/XTENSION/WINFRAME.SLB \
	GEMSYS/MAGIC/XTENSION/WINFRAME.RSC \
	GEMSYS/MAGIC/XTENSION/WINFRAME.INF \
	EXTRAS/ADDMEM.PRG \
	EXTRAS/BIN/ADR.PRG \
	EXTRAS/BIN/BOMB.PRG \
	EXTRAS/BIN/IL0008.PRG \
	EXTRAS/BIN/IL4AFC.PRG \
	EXTRAS/BIN/ILF000.PRG \
	EXTRAS/BIN/PRIV_RTE.PRG \
	EXTRAS/BIN/PRIV_SR.PRG \
	EXTRAS/BIN/TRAP7.PRG \
	EXTRAS/HARDCOPY.PRG \
	EXTRAS/FLOCK_OK/FLOCK_OK.PRG \
	EXTRAS/AES_LUPE/AES_LUPE.APP \
	EXTRAS/AES_LUPE/AES_LUPE.IMG \
	EXTRAS/CLOCK/CLOCK.APP \
	EXTRAS/CLOCK/CLOCK.GEN \
	EXTRAS/CLOCK/CLOCK.INF \
	EXTRAS/CLOCK/CLOCK.MAN \
	EXTRAS/CLOCK/CLOCK.MUP \
	EXTRAS/CLOCK/CLOCKCOL.CPX \
	EXTRAS/CLOCK/MAUS.RUF \
	EXTRAS/CLOCK/README.CAT \
; do
	cp -a "$BUILDROOT/$LANG_UPPER/"$f "$ROOTFS/"$f
done
cp -a "$BUILDROOT/$LANG_UPPER/AUTO/ACCS/"*.PAL "$ROOTFS/AUTO/ACCS/"
cp -a "$BUILDROOT/$LANG_UPPER/AUTO/ACCS/CPX/"*.CPX "$ROOTFS/AUTO/ACCS/CPX/"
cp -a "$BUILDROOT/$LANG_UPPER/AUTO/ACCS/CPZ/"*.CPZ "$ROOTFS/AUTO/ACCS/CPX/"
cp -a "$BUILDROOT/$LANG_UPPER/GEMSYS/GEMDESK/RSC/"* "$ROOTFS/GEMSYS/GEMDESK/RSC/"
cp -a "$BUILDROOT/$LANG_UPPER/GEMSYS/GEMDESK/PAT/"* "$ROOTFS/GEMSYS/GEMDESK/PAT/"
cp -a "$BUILDROOT/$LANG_UPPER/GEMSYS/"*.SYS "$ROOTFS/GEMSYS/"
cp -a "$BUILDROOT/$LANG_UPPER/GEMSYS/"*.OSD "$ROOTFS/GEMSYS/"
cp -a "$BUILDROOT/$LANG_UPPER/GEMSYS/MAGIC/XTENSION/THEMES/"* "$ROOTFS/GEMSYS/MAGIC/XTENSION/THEMES/"


cd "$ROOTFS"

#
# Replacements for MagicOnLinux
#
cp -a "$srcdir/auto/autoexec.bat" AUTO/AUTOEXEC.BAT
cp -a "$srcdir/apps/instmagc/autoexec.bat" AUTOEXEC.BAT
cp -a "$srcdir/apps/instmagc/magx_lin.inf" MAGX.INF
cp -a "$srcdir/kernel/bios/magiclin/localise.sh" LANG/LOCALISE.SH

mv AUTO/ACCS/CPX/MAGXCONF.CPX AUTO/ACCS/CPX/MAGXCONF.CPZ
mv GEMSYS/MAGIC/START/MMXDAEMN.PRX GEMSYS/MAGIC/START/MMXDAEMN.PRG
rm -f AUTO/ACCS/CPX/NCACHE.CPX
rm -f AUTO/ACCS/CPX/NPRNCONF.CPX
rm -f AUTO/ACCS/CPX/MODEM.CPX
rm -f AUTO/ACCS/CPX/PRINTER.CPX
rm -f AUTO/ACCS/CPX/TTSOUND.CPX

cd "$BUILDROOT"

zip -r "$OUT/magiconlinux-${ATAG}.zip" rootfs

rm -rf rootfs

cd "$srcdir"

set +e
